insert into items (name, category, price) values('Item 1', 'Cat1', 250);
insert into items (name, category, price) values('Item 2', 'Cat2', 250);
insert into items (name, category, price) values('Item 3', 'Cat3', 250);
insert into items (name, category, price) values('Item 4', 'Cat4', 250);
insert into items (name, category, price) values('Item 5', 'Cat5', 250);
insert into items (name, category, price) values('Item 6', 'Cat6', 250);
insert into items (name, category, price) values('Item 7', 'Cat7', 250);
insert into items (name, category, price) values('Item 8', 'Cat8', 250);
insert into items (name, category, price) values('Item 9', 'Cat9', 250);
insert into items (name, category, price) values('Item 10', 'Cat10', 250);
insert into items (name, category, price) values('Item 11', 'Cat11', 250);
insert into items (name, category, price) values('Item 12', 'Cat12', 250);

insert into user_items values ('ghaly', 1, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('ghaly', 3, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('ghaly', 5, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('ghaly', 7, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('ghaly', 9, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('ghaly', 11, to_date('14-6-2021','dd-mm-yyyy'), 50);

insert into user_items values ('friend2', 2, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend2', 4, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend2', 5, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend2', 8, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend2', 10, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend2', 11, to_date('14-6-2021','dd-mm-yyyy'), 50);

insert into user_items values ('friend1', 1, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend1', 4, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend1', 6, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend1', 5, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend1', 2, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend1', 3, to_date('14-6-2021','dd-mm-yyyy'), 50);

insert into user_items values ('friend4', 1, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend4', 8, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend4', 10, to_date('14-6-2021','dd-mm-yyyy'), 50);

insert into user_items values ('friend3', 1, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend3', 5, to_date('14-6-2021','dd-mm-yyyy'), 50);
insert into user_items values ('friend3', 2, to_date('14-6-2021','dd-mm-yyyy'), 50);

insert into user_items values ('friend7', 12, to_date('14-6-2021','dd-mm-yyyy'), 50);